### ISSUE TITLE
autogen.sh requires user to press return

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [thkukuk/libnsl#13]
When running autogen.sh I am forced to manually press "Return" to allow it to complete.
`cd .HOST/3.0.0_gcc-10.2.0/libnsl-1.3.0 && \
                PATH=/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/autoconf-2.70/_install/usr/bin:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/automake-1.16/_install/usr/bin:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/gettext-0.20.2/_install/usr/bin:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/libtirpc-1.3.1/_install/usr/bin:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/libtool-2.4.6/_install/usr/bin:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/m4-1.4.18/_install/usr/bin:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/pkg-config-0.29/_install/usr/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin \
                LD_LIBRARY_PATH="/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/autoconf-2.70/_install/usr/lib:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/automake-1.16/_install/usr/lib:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/gettext-0.20.2/_install/usr/lib:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/libtirpc-1.3.1/_install/usr/lib:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/libtool-2.4.6/_install/usr/lib:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/m4-1.4.18/_install/usr/lib:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/perl-5.32.0/_install/usr/lib:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/pkg-config-0.29/_install/usr/lib:/sm_xtools/3.0.0_gcc-10.2.0/tools/x86_64-unknown-linux-gnu/lib64" \
                ACLOCAL_PATH="/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/autoconf-2.70/_install/usr/share/aclocal:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/automake-1.16/_install/usr/share/aclocal:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/libtool-2.4.6/_install/usr/share/aclocal:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/gettext-0.20.2/_install/usr/share/aclocal:/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/pkg-config-0.29/_install/usr/share/aclocal" \
                M4=/build/master/opensource/.HOST/3.0.0_gcc-10.2.0/m4-1.4.18/_install/usr/bin/m4 \
                ./autogen.sh
+ rm -fv ltmain.sh config.sub config.guess config.h.in config.rpath
removed `ltmain.sh'
removed `config.sub'
removed `config.guess'
removed `config.h.in'
removed `config.rpath'
+ gettextize -f
Copying file ABOUT-NLS
Copying file config.rpath
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
Copying file m4/gettext.m4
Copying file m4/host-cpu-c-abi.m4
Copying file m4/iconv.m4
Copying file m4/intlmacosx.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/progtest.m4

Please update po/Makevars so that it defines all the variables mentioned
in po/Makevars.template.
You can then remove po/Makevars.template.

Please run 'aclocal -I m4' to regenerate the aclocal.m4 file.
You need aclocal from GNU automake 1.9 (or newer) to do this.
Then run 'autoconf' to regenerate the configure file.

You will also need config.guess and config.sub, which you can get from the CVS
of the 'config' project at https://savannah.gnu.org/. The commands to fetch them
are
$ wget 'https://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess'
$ wget 'https://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub'

You might also want to copy the convenience header file gettext.h
from the /build/master/opensource/.HOST/3.0.0_gcc-10.2.0/gettext-0.20.2/_install/usr/share/gettext directory into your package.
It is a wrapper around <libintl.h> that implements the configure --disable-nls
option.

Press Return to acknowledge the previous four paragraphs.
`
I've found that I can replace **gettextize** in your autogen.sh with **autopoint** and it runs and builds ok without user intervention, which is kind of annoying when have the build of an entire linux distribution automated, and its insisting on reading input from a tty.

References:
https://bug-gettext.gnu.narkive.com/eeM9iPCY/gettextize-requires-confirmation-from-dev-tty-to-complete
https://man7.org/linux/man-pages/man1/gettextize.1.html
https://linux.die.net/man/1/autopoint

**Comment by awalrond** [comment]
+1

In my case, upgrading gettext from 0.19.8.1 to 0.21 caused the problem.

**Comment by thkukuk** [comment]
Should be fixed for v2.0.0
