### ISSUE TITLE
Hardcoded wrong version

### ISSUE THREAD

**Issue by n-bes** [thkukuk/libnsl#14]
Hi. 

After build ```v1.3.0``` i got ```libnsl.so.2.1.0```, it is hardcoded:
https://github.com/thkukuk/libnsl/blob/958a5b4c11d58d6dfe153d48f2f32fe8c9268fe3/src/Makefile.am#L31-L33

Is it a mistake?

**Comment by thkukuk** [comment]
Would have been nice if you would have written why you think that the ABI version of the shared library should be wrong?
I assume it's not clear to you that the ABI version of a shared library has nothing to do with the version number of the source archive: https://autotools.io/libtool/version.html

**Comment by n-bes** [comment]
Oh, i see. Which version could i take for with```.1``` ABI version?

**Comment by thkukuk** [comment]
libnsl.so.1 is the deprecated version coming from glibc, not from this new standalone one.
