### ISSUE TITLE
bump soname?

### ISSUE THREAD

**Issue by kloczek** [thkukuk/libnsl#16]
Fedora bumped its libnsl SONAME to libnls.so.3.
I'm not sure is that was consulted with you or not but this may create some ABI mess as more and more systems will be using that SONAME.
If you will decide to follow that change IMO it would be good to make new release (2.0.1?)

**Comment by kloczek** [comment]
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/CZGCVKA3UXQT5ANKGR2OQCJJXDEG7KUO/#CZGCVKA3UXQT5ANKGR2OQCJJXDEG7KUO

**Comment by thkukuk** [comment]
I don't understand your request. libnsl-1.x has soname libnsl.so.2 and libnsl-2.0.0 has soname libnsl.so.3.
Why should I bump the soname again only because Fedora is using the new libnsl?
