### ISSUE TITLE
libtool problem - 2.4.2 versus 2.4.6?

### ISSUE THREAD

**Issue by shevegen** [thkukuk/libnsl#6]
I am getting some error running autoconf and/or aclocal, then compiling it.

It says that libtool 2.4.2 is used; I use the latest libtool 2.4.6.

Is there perhaps some hardcoded entry to 2.4.2 in the original source?

I grepped through the source and found:

    ltmain.sh:# libtool (GNU libtool) 2.4.2
    ltmain.sh:#         $progname:  (GNU libtool) 2.4.2
    ltmain.sh:VERSION=2.4.2

I changed this to 2.4.6 then ran autogen again and it compiled
fine. But I think this is not the proper way to handle this, assumingly.

I don't know enough to fix this myself, as I don't know much about
libtool. I only report it just so that you are aware about this. :)

**Comment by thkukuk** [comment]
No idea what exactly you are doing. There is a script "autogen.sh" in the root directory of libnsl, and this is creating everything fine.

But yes, ltmain.sh should not be part of git at all ...

**Comment by thkukuk** [comment]
Removed the file.
