### ISSUE TITLE
gettext infrastructure mismatch

### ISSUE THREAD

**Issue by scsijon** [thkukuk/libnsl#8]
Downloaded v 1.2.0 and raw zip and both are giving me the same error whe  trying to build.

*** error: gettext infrastructure mismatch: using a makefile.in.in from a getetxt version 0.19 but the autoconf macros are from gettext version 0.20

are we due for an update or something again?

thanks

**Comment by hasso** [comment]
#9 should fix it.

**Comment by scsijon** [comment]
nothing so far, or is there a push or something needed to happen or cycle through and i'm rushing things?

thanks

**Comment by thkukuk** [comment]
Not everybody is sitting 24 hours/day on a computer, I'm currently on FTO with limited network access. There will not much happen the next 7-10 days.

**Comment by thkukuk** [comment]
Should be fixed now.

**Comment by scsijon** [comment]
just a note that 1.3.0 builds nicely on T2sde, many thanks
